1) Launch Chimera through structureViz and open up PDB file
2) Create a RIN
3) Load Contact Network and choose the RIN to associate with
	3a) This should open up a Results Panel with a Tstress slider
	3b) For each position on the slider, show the Connected Components
		* Each component should be in a different color
		* RIN nodes should be colored to correspond to the connected components
		* Clicking on a component, selects those residues in the RIN
